// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soa.Data;

#nullable disable

namespace Soa.Migrations
{
    [DbContext(typeof(SoaContext))]
    [Migration("20221124182235_check")]
    partial class check
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Soa.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("Authorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("Soa.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Authorname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Genretype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Description = " page turner",
                            GenreId = 1,
                            Genretype = "Fiction",
                            Price = 5.99m,
                            PublishDate = new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gangsta Granny Strikes Again!"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Description = "Throughout the series, Harry is described as having his father's perpetually untidy black hair, his mother's bright green eyes, and a lightning bolt-shaped scar on his forehead. He is further described as small and skinny for his age with a thin face and knobbly knees, and he wears Windsor glasses.",
                            GenreId = 2,
                            Genretype = "Fantasy",
                            Price = 5.99m,
                            PublishDate = new DateTime(2000, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter collection"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3,
                            Description = "Naomi, Melvin, Pedro, and Poppy are just a few of the twenty-one rambunctious, funny, and talented baby frogs who share their stories in the Cat Kid Comic Club. Can Li’l Petey, Molly, and Flippy help the students express themselves through comics? The adventures in class and on paper unwind with mishaps and hilarity as the creative baby frogs experience the mistakes and progress that come with practice and persistence.",
                            GenreId = 3,
                            Genretype = "kid",
                            Price = 12.95m,
                            PublishDate = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cat Kid Comic Club series"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4,
                            Description = "Mr Fox, a family man, goes back to his ways of stealing, unable to resist his animal instincts. However, he finds himself trapped when three farmers decide to kill him and his kind.",
                            GenreId = 4,
                            Genretype = "action",
                            Price = 6.50m,
                            PublishDate = new DateTime(2009, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Mr. Fox"
                        });
                });

            modelBuilder.Entity("Soa.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
